CREATE UNIQUE INDEX IF NOT EXISTS UX_c64558_Id ON sk.AssessmentAdministration(Id);

CREATE UNIQUE INDEX IF NOT EXISTS UX_9e9b7e_Id ON sk.CrisisDetails(Id);

CREATE UNIQUE INDEX IF NOT EXISTS UX_bc1d0a_Id ON sk.PostGraduateActivity(Id);

